# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

straw_R <- function(argv) {
    .Call('_v4C_straw_R', PACKAGE = 'v4C', argv)
}

